name: Run frontend tests and generate coverage.
on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./front
        steps:
          - name: Checkout code
            uses: actions/checkout@v5

          - name: Setup Node.js
            uses: actions/setup-node@v5
            with:
              node-version: '18'

          - name: Install dependencies
            run: npm ci

          - name: Run tests with coverage
            run: npx ng test --no-progress --watch=false --browsers=ChromeHeadlessCI --code-coverage
          
          - name: Upload coverage report
            uses: actions/upload-artifact@v6
            with:
              name: frontend-coverage
              path: front/coverage/bobapp/
              retention-days: 7

          - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
            with:
              fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          - name: SonarQube Scan
            uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
